# Generated by Django 5.1.7 on 2025-03-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qr_generator',
            options={'verbose_name': 'QR CODE', 'verbose_name_plural': 'QR CODES'},
        ),
    ]
